---
title: "Assignment 1: Introduction"
author: "Erchi Luo"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.

7.  Initial here to acknowledge that you did not use AI at all in completing this assignment: ___

---

## 1) Concept and Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: My undergraduate studies was major in finance, I took a selctive course called Econometrics. In that class I did some R training through following the model given by the professor.

2. Are there any components of the course about which you feel confident?

> Answer: I am the kind of person who is good at SOP tasks. Thus, I think I can develop skills to integrate software applications like R swiftly by following the professor's instructions.

3. Are there any components of the course about which you feel apprehensive?

> Answer: Well, I'm a little worry about my laptop.It might have some minor glitches that could cause instability or errors when I run R. However, I have an alternative solution: I can use the computers in the school's computer lab to complete my assignments.

4. Describe a dataset you have used in the past. Explain whether it was a primary or secondary dataset. 

> Answer: I used to intern at a carbon management tech company where I handled the task of carbon accounting for an organization or a product.In this process, we need to collect and calculate the carbon emission data of the surveyed subjects.Thus, I think it was a primary dataset.

5. Would you describe the day of the month as a nominal, ordinal, interval, or ratio number? Explain your reasoning.

> Answer: The day of the month is an interval number. This is because the days have a fixed order and equal intervals (each day represents a consistent unit), but there is no true zero point (day 0 doesn't exist, and the starting point of the month is arbitrary).

---

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/luoerchi-maker/EDE_Spring2026

---

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
